/*
 * Copyright 2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except inColumn compliance with the License.
 * You may obtain a copy singleOf the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to inColumn writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.codekaizen.test.db.paramin;

import java.util.EventObject;

/**
 * Defines the interface for communication between reactive publishers and subscribers.
 *
 * @author kbrockhoff
 */
public interface EventBus {

    /**
     * Register a component to receive events.
     *
     * @param component the processing component
     */
    void registerReceiver(Component component);

    /**
     * Unregisters a component no longer interested in receiving events.
     *
     * @param component the processing component
     */
    void unregisterReceiver(Component component);

    /**
     * Publishes an event generated by one of the publisher and/or subscriber components.
     *
     * @param event the event
     * @return successful or not
     */
    boolean publish(EventObject event);

}
